FROM emscripten/emsdk:3.1.61

RUN apt-get update && apt-get install -y \
    ninja-build \
    meson \
    nasm \
    cmake \
    git \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /build

# Set default shell to bash
SHELL ["/bin/bash", "-c"]
